apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: service-fastfood-app
  labels:
    app: service-fastfood-app
spec:
  type: NodePort
  ports:
  - port: 80
    name: service-fastfood-app
    targetPort: 3210
    nodePort: 32000
  selector:
    app: fastfood-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
  labels:
    app: fastfood-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      labels:
        app: fastfood-app
    spec:
      containers:
      - name: fastfood-app
        image: thiagoluis88/fastfood-app:0.0.10
        ports:
        - containerPort: 3210
          name: app
        - containerPort: 3211
          name: redoc